#!/usr/bin/env python3
"""Render meta/logs/ledger.yaml into human-readable views.

Outputs:
  meta/logs/ledger.md                       one section per business problem
                                            (Mermaid chain + step table), the
                                            cross-cutting chain, an open-items
                                            table, and trailer notes.
  site/tributary/_includes/chain_<id>.qmd   the Mermaid chain alone, for the
                                            method page and the per-page
                                            callouts to include.
  site/tributary/_includes/record_<ID>.qmd  a record extracted verbatim from
                                            its log (--extract D8 P-005 ...),
                                            so the site never paraphrases it.

Usage:
  .venv/bin/python meta/tools/render_ledger.py [--extract D8 P-005 P-008 P-010 P-011]
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
LEDGER = REPO_ROOT / "meta" / "logs" / "ledger.yaml"
OUT_MD = REPO_ROOT / "meta" / "logs" / "ledger.md"
INCLUDES = REPO_ROOT / "site" / "tributary" / "_includes"
LOG_FOR_PREFIX = {"INT": "interventions.md", "P": "prompts.md"}
REPO_URL = "https://github.com/JordanBeary/tributary/blob/main/"


def record_link(ref: str) -> str:
    """Markdown link for a ref: record ids point at their log; paths at the repo."""
    if re.match(r"^(INT|P)-\d{3}$", ref):
        return f"[{ref}](https://github.com/JordanBeary/tributary/blob/main/meta/logs/{LOG_FOR_PREFIX[ref.split('-')[0]]})"
    if re.match(r"^[ABCDQ]\d{1,2}$", ref):
        return f"[{ref}]({REPO_URL}meta/logs/decisions.md)"
    if re.match(r"^[0-9a-f]{7,40}$", ref):
        return f"[`{ref}`](https://github.com/JordanBeary/tributary/commit/{ref})"
    return f"[`{ref}`]({REPO_URL}{ref})"


def mermaid(problem: dict) -> str:
    """Linear left-to-right chain; human steps get a distinct class."""
    lines = ["flowchart LR"]
    human_nodes = []
    for i, step in enumerate(problem["steps"], 1):
        label = step["label"].replace('"', "'")
        text = f"{step['ref']}<br/>{label}"
        lines.append(f'  s{i}["{text}"]')
        if step["actor"] == "human":
            human_nodes.append(f"s{i}")
    for i in range(1, len(problem["steps"])):
        lines.append(f"  s{i} --> s{i + 1}")
    lines.append("  classDef human fill:#f1e6d4,stroke:#8a5a2b,color:#1f2933;")
    lines.append("  classDef agent fill:#eef2f7,stroke:#3b5b8c,color:#1f2933;")
    lines.append("  classDef harness fill:#ffffff,stroke:#7b8794,color:#1f2933,stroke-dasharray:4 2;")
    for actor in ("human", "agent", "harness"):
        nodes = [f"s{i}" for i, s in enumerate(problem["steps"], 1) if s["actor"] == actor]
        if nodes:
            lines.append(f"  class {','.join(nodes)} {actor};")
    return "\n".join(lines)


def step_table(problem: dict) -> str:
    rows = ["| # | Actor | Kind | Record | Date | What happened |", "| --- | --- | --- | --- | --- | --- |"]
    for i, s in enumerate(problem["steps"], 1):
        rows.append(f"| {i} | {s['actor']} | {s['kind']} | {record_link(s['ref'])} | {s['date']} | {s['label']} |")
    return "\n".join(rows)


def render_md(data: dict) -> str:
    out = [
        "# Interaction ledger",
        "",
        "*Generated by `meta/tools/render_ledger.py` from `meta/logs/ledger.yaml`; do not edit by hand. "
        "Each chain links existing records (prompts P, interventions INT, decisions A/B/C/D) in the order "
        "they happened, from the business question to the published finding. Human steps are shaded in the diagrams.*",
        "",
        "## Open items",
        "",
        "| Record | Kind | Status | Since | Owner | Where the ask is | Note |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for it in data.get("open_items", []):
        out.append(f"| {record_link(it['ref'])} | {it['kind']} | {it['status']} | {it['since']} | {it['owner']} | {record_link(it['ask'])} | {it.get('note', '')} |")
    out.append("")
    if data.get("resolved_items"):
        out += ["## Resolved", "",
                "| Record | Resolved | Disposition |", "| --- | --- | --- |"]
        for it in data["resolved_items"]:
            out.append(f"| {record_link(it['ref'])} | {it['resolved']} | {it.get('note', '')} |")
        out.append("")
    for p in data["problems"]:
        out += [
            f"## {p['title']}",
            "",
            f"**Question.** {p['question']}",
            "",
            f"**Finding.** {p['finding']} Sources: " + ", ".join(record_link(r) for r in p.get("finding_refs", [])) + ".",
            "",
            "```mermaid",
            mermaid(p),
            "```",
            "",
            step_table(p),
            "",
        ]
    for p in data.get("cross_cutting", []):
        out += [f"## {p['title']}", "", "```mermaid", mermaid(p), "```", "", step_table(p), ""]
    if data.get("notes"):
        out += ["## Trailer notes", ""]
        for n in data["notes"]:
            out.append(f"- {record_link(n['ref'])}: {n['note']}")
        out.append("")
    return "\n".join(out)


def write_includes(data: dict) -> list[Path]:
    INCLUDES.mkdir(parents=True, exist_ok=True)
    written = []
    for p in data["problems"] + data.get("cross_cutting", []):
        path = INCLUDES / f"chain_{p['id']}.qmd"
        path.write_text(
            f"<!-- generated by meta/tools/render_ledger.py from meta/logs/ledger.yaml; do not edit -->\n"
            f"```{{mermaid}}\n%%| fig-cap: \"{p['title']}: the chain of records from question to finding. Shaded nodes are the human's steps.\"\n{mermaid(p)}\n```\n"
        )
        written.append(path)
    return written


def extract_record(rec_id: str) -> str:
    """Return a record's body verbatim (heading dropped) from its log."""
    if rec_id.startswith(("INT-", "P-")):
        path = REPO_ROOT / "meta" / "logs" / LOG_FOR_PREFIX[rec_id.split("-")[0]]
        start = re.compile(rf"^## {re.escape(rec_id)}\b")
        stop = re.compile(r"^## ")
    else:
        path = REPO_ROOT / "meta" / "logs" / "decisions.md"
        start = re.compile(rf"^### {re.escape(rec_id)}\b")
        stop = re.compile(r"^##+ ")
    lines = path.read_text().splitlines()
    body: list[str] = []
    capturing = False
    heading = ""
    for line in lines:
        if not capturing and start.match(line):
            capturing, heading = True, line.lstrip("# ").strip()
            continue
        if capturing and stop.match(line):
            break
        if capturing:
            body.append(line)
    if not capturing:
        raise SystemExit(f"record {rec_id} not found in {path}")
    text = "\n".join(body).strip("\n")
    return (f"<!-- generated by meta/tools/render_ledger.py --extract {rec_id}; verbatim from {path.relative_to(REPO_ROOT)}; do not edit -->\n"
            f"**{heading}**\n\n{text}\n")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--extract", nargs="*", default=[], help="record ids to extract verbatim into site includes")
    args = ap.parse_args()
    data = yaml.safe_load(LEDGER.read_text())
    OUT_MD.write_text(render_md(data))
    written = write_includes(data)
    for rec_id in args.extract:
        path = INCLUDES / f"record_{rec_id}.qmd"
        path.write_text(extract_record(rec_id))
        written.append(path)
    print(f"wrote {OUT_MD.relative_to(REPO_ROOT)} and {len(written)} include(s) under {INCLUDES.relative_to(REPO_ROOT)}/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
